In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

%matplotlib inline

While scraping I:
    - dropped player duplicates and kept the fist row 
    - added the URL slug to the dataframe
    - dropped the empty column that was imported from chart

# EDA UGH

# Unupervised I'M TRYING

In [30]:
from sklearn.datasets import make_blobs
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

ModuleNotFoundError: No module named 'lib.cluster'

In [5]:
season1819 = pd.read_csv('season1819.csv', index_col=False)
season1819.drop(columns = 'Unnamed: 0', inplace= True)
season1819.fillna(0, inplace = True)

In [8]:
season1819.columns

Index(['Player', 'Pos', 'Age', 'Tm', 'G', 'GS', 'MP', 'FG', 'FGA', 'FG%', '3P',
       '3PA', '3P%', '2P', '2PA', '2P%', 'FT', 'FTA', 'FT%', 'ORB', 'DRB',
       'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', 'Unnamed: 29', 'ORtg',
       'DRtg', 'url_list'],
      dtype='object')

In [15]:
df = season1819.drop(['MP', 'url_list', 'Tm', 'Unnamed: 29'], axis = 1)
df = df[df['G'] > 40]

In [16]:
df.shape

(386, 28)

In [17]:
X = df.drop(['Player', 'Pos', 'G'], axis = 1)
y = df['Pos']

In [18]:
#scaling data
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [21]:
pca = PCA(n_components = 2)
pca.fit(X_scaled)

X_pca = pca.transform(X_scaled)
print("Cumulative Explained Variance:", pca.explained_variance_ratio_.sum())

Cumulative Explained Variance: 0.5697007173905764

# Kmeans

In [31]:
myKMC = KMeans(n_clusters = 5)

In [33]:
myKMC.fit(df.drop(['Player', 'Pos', 'G'], axis = 1))

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
       n_clusters=5, n_init=10, n_jobs=None, precompute_distances='auto',
       random_state=None, tol=0.0001, verbose=0)

In [34]:
myKMC.cluster_centers_

array([[ 26.68131868,  73.79120879,   9.64835165,  20.27582418,
          0.47894505,   2.46923077,   6.70549451,   0.32810989,
          7.18791209,  13.56483516,   0.52596703,   4.6       ,
          5.83846154,   0.78826374,   2.17362637,   7.5021978 ,
          9.68021978,   5.73296703,   1.56923077,   1.07142857,
          3.0956044 ,   3.63296703,  26.37802198, 114.01098901,
        109.36263736],
       [ 26.36220472,   5.38582677,   6.92677165,  16.27007874,
          0.42476378,   2.39133858,   6.98031496,   0.32396063,
          4.53307087,   9.28267717,   0.49046457,   2.62519685,
          3.48503937,   0.74933858,   1.53779528,   5.93070866,
          7.47322835,   4.31496063,   1.38818898,   0.73149606,
          2.43858268,   4.41732283,  18.86929134, 105.51968504,
        111.48031496],
       [ 26.10606061,  49.92424242,   7.41363636,  16.41969697,
          0.45236364,   2.0969697 ,   5.93484848,   0.32472727,
          5.31818182,  10.48636364,   0.50227273,   3.06515152,
          3.96818182,   0.77322727,   1.89545455,   6.79393939,
          8.68787879,   4.48030303,   1.54848485,   0.95757576,
          2.51515152,   4.19090909,  19.99090909, 108.95454545,
        111.51515152],
       [ 27.28571429,   7.61904762,   7.05      ,  12.95952381,
          0.54492857,   0.86428571,   2.42380952,   0.21811905,
          6.18333333,  10.54047619,   0.5837619 ,   3.19047619,
          4.52619048,   0.70957143,   3.98571429,   8.64761905,
         12.64285714,   3.41428571,   1.37857143,   1.59047619,
          2.07857143,   5.66666667,  18.14047619, 121.9047619 ,
        108.61904762],
       [ 25.5       ,  26.95      ,   7.36666667,  16.195     ,
          0.45443333,   2.15666667,   6.145     ,   0.31903333,
          5.215     ,  10.04166667,   0.5162    ,   2.71333333,
          3.61333333,   0.75088333,   2.21666667,   6.96166667,
          9.18166667,   4.04333333,   1.43333333,   0.97666667,
          2.38166667,   4.30833333,  19.60833333, 109.7       ,
        111.63333333]])

In [43]:
myKMC.labels_

array([0, 4, 0, 0, 0, 1, 2, 0, 1, 4, 0, 2, 0, 0, 1, 1, 2, 1, 0, 2, 4, 0,
       3, 4, 0, 4, 1, 1, 1, 4, 3, 2, 3, 4, 0, 1, 0, 4, 0, 1, 0, 2, 2, 2,
       4, 1, 0, 2, 4, 1, 1, 4, 2, 2, 2, 1, 4, 0, 2, 1, 4, 0, 1, 1, 2, 0,
       3, 3, 4, 1, 1, 1, 1, 0, 1, 0, 0, 3, 1, 4, 4, 1, 1, 3, 1, 0, 1, 0,
       3, 2, 1, 1, 0, 3, 1, 3, 1, 0, 1, 2, 0, 4, 2, 0, 4, 0, 4, 1, 1, 0,
       3, 0, 1, 4, 0, 0, 0, 4, 4, 0, 1, 0, 2, 2, 0, 2, 1, 0, 0, 0, 2, 2,
       1, 0, 1, 0, 2, 1, 1, 1, 2, 0, 0, 2, 0, 2, 3, 1, 2, 0, 0, 2, 1, 4,
       4, 4, 3, 4, 0, 3, 1, 1, 1, 1, 0, 0, 2, 4, 3, 2, 2, 0, 2, 1, 2, 3,
       1, 0, 2, 0, 2, 1, 1, 2, 4, 3, 1, 0, 0, 3, 1, 4, 1, 1, 4, 1, 0, 3,
       4, 0, 2, 1, 1, 4, 4, 1, 3, 4, 2, 1, 4, 1, 1, 1, 2, 0, 2, 0, 4, 3,
       4, 0, 3, 3, 0, 1, 1, 3, 3, 0, 4, 0, 1, 1, 1, 1, 1, 3, 2, 1, 0, 2,
       0, 1, 1, 0, 2, 3, 4, 0, 1, 1, 1, 0, 4, 0, 1, 1, 4, 2, 1, 3, 2, 0,
       1, 1, 1, 1, 4, 1, 1, 3, 3, 4, 1, 0, 3, 1, 1, 1, 4, 1, 2, 4, 0, 4,
       3, 4, 1, 1, 2, 2, 3, 3, 3, 2, 4, 4, 3, 1, 3, 1, 2, 0, 0, 1, 1, 4,
       3, 4, 1, 1, 1, 0, 0, 3, 2, 4, 2, 1, 1, 1, 1, 1, 1, 0, 4, 1, 2, 2,
       0, 0, 1, 1, 2, 2, 1, 3, 1, 1, 1, 1, 0, 2, 2, 2, 3, 1, 0, 2, 1, 1,
       0, 1, 0, 1, 0, 3, 4, 4, 2, 0, 1, 1, 4, 0, 1, 2, 4, 0, 2, 2, 0, 4,
       1, 0, 1, 2, 1, 1, 1, 0, 0, 2, 4, 4])

In [44]:
# attach predicted cluster to original points
df['cluster'] = myKMC.labels_
df.head()

,Player,Pos,Age,G,GS,FG,FGA,FG%,3P,3PA,...,TRB,AST,STL,BLK,TOV,PF,PTS,ORtg,DRtg,cluster
3,Steven Adams,C,25.0,80.0,80.0,8.4,14.1,0.595,0.0,0.0,...,13.3,2.2,2.0,1.3,2.4,3.6,19.4,120.0,106.0,0
4,Bam Adebayo,C,21.0,82.0,28.0,7.2,12.4,0.576,0.1,0.4,...,15.2,4.7,1.8,1.7,3.1,5.2,18.6,120.0,104.0,4
7,LaMarcus Aldridge,C,33.0,81.0,81.0,12.4,24.0,0.519,0.2,0.8,...,13.5,3.5,0.8,1.9,2.6,3.3,31.4,117.0,110.0,0
10,Jarrett Allen,C,20.0,80.0,80.0,7.6,12.9,0.590,0.1,1.0,...,15.3,2.5,1.0,2.7,2.3,4.2,19.8,123.0,106.0,0
12,Al-Farouq Aminu,PF,28.0,81.0,81.0,5.4,12.5,0.433,2.0,5.9,...,12.9,2.2,1.4,0.7,1.5,3.0,16.1,118.0,109.0,0

In [45]:
df.groupby('cluster').mean()

,Age,G,GS,FG,FGA,FG%,3P,3PA,3P%,2P,...,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,ORtg,DRtg
cluster,,,,,,,,,,,,,,,,,,,,,
0,26.681319,74.846154,73.791209,9.648352,20.275824,0.478945,2.469231,6.705495,0.328110,7.187912,...,7.502198,9.680220,5.732967,1.569231,1.071429,3.095604,3.632967,26.378022,114.010989,109.362637
1,26.362205,59.165354,5.385827,6.926772,16.270079,0.424764,2.391339,6.980315,0.323961,4.533071,...,5.930709,7.473228,4.314961,1.388189,0.731496,2.438583,4.417323,18.869291,105.519685,111.480315
2,26.106061,60.636364,49.924242,7.413636,16.419697,0.452364,2.096970,5.934848,0.324727,5.318182,...,6.793939,8.687879,4.480303,1.548485,0.957576,2.515152,4.190909,19.990909,108.954545,111.515152
3,27.285714,64.452381,7.619048,7.050000,12.959524,0.544929,0.864286,2.423810,0.218119,6.183333,...,8.647619,12.642857,3.414286,1.378571,1.590476,2.078571,5.666667,18.140476,121.904762,108.619048
4,25.500000,61.516667,26.950000,7.366667,16.195000,0.454433,2.156667,6.145000,0.319033,5.215000,...,6.961667,9.181667,4.043333,1.433333,0.976667,2.381667,4.308333,19.608333,109.700000,111.633333

In [48]:
centroids = pd.DataFrame(
    scaler.inverse_transform(myKMC.cluster_centers_),
    columns=[X]
)

# Trying again

In [36]:
from sklearn.datasets import make_blobs
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
from sklearn.preprocessing import StandardScaler

import numpy as np
import pandas as pd

import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib

matplotlib.style.use('ggplot')

,Age,GS,FG,FGA,FG%,3P,3PA,3P%,2P,2PA,...,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,ORtg,DRtg
3,25.0,80.0,8.4,14.1,0.595,0.0,0.0,0.000,8.4,14.1,...,6.5,13.3,2.2,2.0,1.3,2.4,3.6,19.4,120.0,106.0
4,21.0,28.0,7.2,12.4,0.576,0.1,0.4,0.200,7.1,12.0,...,11.0,15.2,4.7,1.8,1.7,3.1,5.2,18.6,120.0,104.0
7,33.0,81.0,12.4,24.0,0.519,0.2,0.8,0.238,12.3,23.2,...,9.0,13.5,3.5,0.8,1.9,2.6,3.3,31.4,117.0,110.0
10,20.0,80.0,7.6,12.9,0.590,0.1,1.0,0.133,7.5,11.9,...,10.9,15.3,2.5,1.0,2.7,2.3,4.2,19.8,123.0,106.0
12,28.0,81.0,5.4,12.5,0.433,2.0,5.9,0.343,3.4,6.6,...,10.5,12.9,2.2,1.4,0.7,1.5,3.0,16.1,118.0,109.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
724,30.0,81.0,8.7,16.5,0.527,1.0,2.9,0.349,7.7,13.7,...,6.5,10.3,4.0,2.4,0.7,2.4,3.8,20.1,113.0,106.0
725,20.0,81.0,9.7,23.2,0.418,2.9,8.9,0.324,6.8,14.3,...,4.4,5.6,12.1,1.3,0.3,5.7,2.6,28.6,107.0,117.0
726,26.0,47.0,7.4,13.5,0.551,0.2,0.9,0.273,7.2,12.6,...,8.7,13.0,4.0,1.5,1.6,2.4,6.4,19.4,123.0,111.0
730,22.0,25.0,8.4,15.2,0.553,0.0,0.0,0.000,8.4,15.2,...,9.7,14.7,2.4,0.6,1.0,2.8,5.2,21.1,116.0,117.0
731,21.0,37.0,9.6,17.1,0.559,0.0,0.0,0.000,9.6,17.1,...,11.1,16.3,2.8,0.6,2.3,3.2,6.2,23.7,116.0,108.0